-- a) Quais componentes cada professor está ministrando?
SELECT P.NOME, C.NOME FROM AT02_PROFESSORES P JOIN AT02_COMPONENTES C ON (P.ID = C.ID_PROFESSOR)

-- b) Quais componentes cada aluno está matriculado?
SELECT A.NOME,C.NOME 
FROM AT02_ALUNOS A JOIN AT02_ALUNOS_COMPONENTES AC ON (A.ID=AC.ID_ALUNO) JOIN AT02_COMPONENTES C ON (C.ID=AC.ID_COMPONENTE)
ORDER BY A.NOME, C.NOME

-- c) Quais são os alunos do componente "x"? (x é um componente que você inseriu)
SELECT A.NOME,C.NOME 
FROM AT02_ALUNOS A JOIN AT02_ALUNOS_COMPONENTES AC ON (A.ID=AC.ID_ALUNO) JOIN AT02_COMPONENTES C ON (C.ID=AC.ID_COMPONENTE)
WHERE C.NOME='BD2'
ORDER BY A.NOME, C.NOME
-- d) Qual o professor do componente "x"? (x é um componente que você inseriu)
SELECT P.NOME, C.NOME FROM AT02_PROFESSORES P JOIN AT02_COMPONENTES C ON (P.ID = C.ID_PROFESSOR) WHERE C.NOME='BD2'
-- e) Quais os horários do aluno "x"? (x é um aluno que você inseriu)
SELECT A.NOME,C.HORARIO 
FROM AT02_ALUNOS A JOIN AT02_ALUNOS_COMPONENTES AC ON (A.ID=AC.ID_ALUNO) JOIN AT02_COMPONENTES C ON (C.ID=AC.ID_COMPONENTE)
WHERE A.NOME='ANA DE SOUZA'
ORDER BY A.NOME, C.NOME
-- f) Quais os horários do professor "x"? (x é um professor que você inseriu)
SELECT P.NOME, C.HORARIO
FROM AT02_PROFESSORES P JOIN AT02_COMPONENTES C ON (P.ID = C.ID_PROFESSOR)
WHERE P.NOME = 'GUSTAVO HENRIQUE'

-- a) Quantos alunos tem em cada componente?
SELECT COUNT(A.NOME) ALUNOS, C.NOME
FROM AT02_ALUNOS A JOIN AT02_ALUNOS_COMPONENTES AC ON (A.ID=AC.ID_ALUNO) JOIN AT02_COMPONENTES C ON (C.ID=AC.ID_COMPONENTE)
GROUP BY C.ID

-- b) Quantos alunos tem cada professor?
SELECT P.NOME, COUNT(A.NOME) 
FROM 
	AT02_ALUNOS A 
	JOIN AT02_ALUNOS_COMPONENTES AC ON (A.ID=AC.ID_ALUNO) 
	JOIN AT02_COMPONENTES C ON (C.ID=AC.ID_COMPONENTE)
	JOIN AT02_PROFESSORES P ON (P.ID=C.ID_PROFESSOR)
GROUP BY P.ID

-- c) Algum professor não tem nenhuma turma?
SELECT P.NOME, C.NOME FROM AT02_PROFESSORES P LEFT JOIN AT02_COMPONENTES C ON (P.ID = C.ID_PROFESSOR)
WHERE C.NOME IS NULL